# set the operating mode of the dynamixel
# list of control modes:
#   Current Control Mode            = 0
#   Velocity Control Mode           = 1
#   Position Control Mode           = 3
#   Extended Pos. Control Mode      = 4
#   Current-Base Pos. Control Mode  = 5
#   PWM Control Mode                = 16

# Communication -----------------------------------
device: '/dev/ttyDXL_follower'
baudrate: 3000000
version: 2
control_freq: 100

# Parameters ---------------------------------------
arm/joint1:
  id: 21
  min_position: 1023
  max_position: 3073
  home_position: 2048
  current_limit: 100
  operating_mode: 3

arm/joint2:
  id: 22
  min_position: 1023
  max_position: 3073
  home_position: 1000
  current_limit: 100
  operating_mode: 3

arm/joint3:
  id: 23
  min_position: 1023
  max_position: 3073
  home_position: 2880
  current_limit: 100
  operating_mode: 3

arm/joint4:
  id: 24
  min_position: 1023
  max_position: 3073
  home_position: 2210
  current_limit: 100
  operating_mode: 3

arm/joint5:
  id: 25
  min_position: 1023
  max_position: 3073
  home_position: 1515
  current_limit: 100
  operating_mode: 3
